name:  MoveTK-CI-Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: microsoft/vcpkg
            path: vcpkg-202007
            ref: '2020.07'
     
      # Checkout repository
      - uses: actions/checkout@v2
        with:
            repository: heremaps/movetk
            submodules: recursive
            path: movetk   
     
      # Get the ninja generator
      - uses: seanmiddleditch/gha-setup-ninja@master
     
      - name: Set vcpkg's response file path used as part of cache's key.
        uses: lukka/set-shell-env@master
        with:
          VCPKGRESPONSEFILE: ${{ github.workspace }}\movetk\src\vcpkg_response_file.txt
      
      - name: Get specific CMake version (3.17.1)
        uses: lukka/get-cmake@v3.17.1
      
      # Restore from cache the previously built ports. If "cache miss", then provision vcpkg, install desired ports, finally cache everything for the next run.        
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          # Response file stored in source control, it provides the list of ports and triplet(s).
          vcpkgArguments: '@${{ env.VCPKGRESPONSEFILE }}'
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}\vcpkg-202007'
          vcpkgGitCommitId: '56fffbe49dfb4dd8fae0940f272c5fd2b86be991'
          # Since the cache must be invalidated when content of the response file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( env.VCPKGRESPONSEFILE ) }}
     
      # Build movetk
      - name: Run CMake with Ninja
        uses: lukka/run-cmake@main
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}\movetk\CMakeLists.txt'
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: '-GNinja -DVCPKG_TARGET_TRIPLET=x64-windows -DWITH_CGAL_BACKEND=OFF -DBUILD_DOC=ON'   
